-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.Account (
  id text NOT NULL,
  userId text NOT NULL,
  provider USER-DEFINED NOT NULL,
  providerAccountId text NOT NULL,
  accessToken text,
  refreshToken text,
  expiresAt timestamp without time zone,
  tokenType text,
  scope text,
  idToken text,
  sessionState text,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt timestamp without time zone NOT NULL,
  CONSTRAINT Account_pkey PRIMARY KEY (id),
  CONSTRAINT Account_userId_fkey FOREIGN KEY (userId) REFERENCES public.User(id)
);
CREATE TABLE public.AnalyticsEvent (
  id text NOT NULL,
  userId text,
  cardId text,
  eventName text NOT NULL,
  eventCategory text NOT NULL,
  properties jsonb,
  sessionId text,
  pageUrl text,
  pageName text,
  pageTitle text,
  referrer text,
  deviceType USER-DEFINED NOT NULL DEFAULT 'UNKNOWN'::"DeviceType",
  browser text,
  browserVersion text,
  os text,
  osVersion text,
  screenWidth integer,
  screenHeight integer,
  isMobile boolean,
  ipCountry text,
  ipCity text,
  ipRegion text,
  utmSource text,
  utmMedium text,
  utmCampaign text,
  utmTerm text,
  utmContent text,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT AnalyticsEvent_pkey PRIMARY KEY (id),
  CONSTRAINT AnalyticsEvent_userId_fkey FOREIGN KEY (userId) REFERENCES public.User(id)
);
CREATE TABLE public.AuditLog (
  id text NOT NULL,
  userId text,
  action USER-DEFINED NOT NULL,
  entityType text NOT NULL,
  entityId text,
  description text,
  changes jsonb,
  ipAddress text,
  userAgent text,
  sessionId text,
  deviceType USER-DEFINED,
  metadata jsonb,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT AuditLog_pkey PRIMARY KEY (id),
  CONSTRAINT AuditLog_userId_fkey FOREIGN KEY (userId) REFERENCES public.User(id)
);
CREATE TABLE public.BusinessProfile (
  id text NOT NULL,
  userId text NOT NULL,
  name text NOT NULL,
  slug text NOT NULL,
  title text,
  company text,
  tagline text,
  profileImageUrl text,
  coverImageUrl text,
  brandLogoUrl text,
  logoPosition USER-DEFINED NOT NULL DEFAULT 'TOP_LEFT'::"LogoPosition",
  primaryEmail text,
  secondaryEmail text,
  primaryPhone text,
  secondaryPhone text,
  website text,
  address text,
  city text,
  state text,
  country text,
  postalCode text,
  latitude double precision,
  longitude double precision,
  industry text,
  department text,
  jobLevel text,
  yearFounded integer,
  companySize text,
  appointmentEnabled boolean NOT NULL DEFAULT false,
  appointmentUrl text,
  appointmentLabel text DEFAULT 'Book a Call'::text,
  collectContactsEnabled boolean NOT NULL DEFAULT true,
  collectNotesEnabled boolean NOT NULL DEFAULT false,
  contactFormLabel text DEFAULT 'Add to Contact'::text,
  headingText text,
  headingBodyText text,
  contactUsHeading text,
  contactUsBodyText text,
  metaTitle text,
  metaDescription text,
  ogImage text,
  shareUrl text,
  customCss text,
  customJs text,
  completionScore integer NOT NULL DEFAULT 0,
  engagementScore integer NOT NULL DEFAULT 0,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt timestamp without time zone NOT NULL,
  publishedAt timestamp without time zone,
  deletedAt timestamp without time zone,
  CONSTRAINT BusinessProfile_pkey PRIMARY KEY (id),
  CONSTRAINT BusinessProfile_userId_fkey FOREIGN KEY (userId) REFERENCES public.User(id)
);
CREATE TABLE public.Card (
  id text NOT NULL,
  userId text NOT NULL,
  businessProfileId text NOT NULL,
  name text NOT NULL,
  cardType USER-DEFINED NOT NULL DEFAULT 'QR'::"CardType",
  status USER-DEFINED NOT NULL DEFAULT 'DRAFT'::"CardStatus",
  slug text NOT NULL,
  shareUrl text NOT NULL,
  shortUrl text,
  headingText text,
  headingBodyText text,
  nfcUid text,
  nfcEnabled boolean NOT NULL DEFAULT false,
  nfcWriteCount integer NOT NULL DEFAULT 0,
  nfcLastWrittenAt timestamp without time zone,
  qrEnabled boolean NOT NULL DEFAULT true,
  qrConfig jsonb,
  qrMatrix bytea,
  qrScanCount integer NOT NULL DEFAULT 0,
  qrLastScannedAt timestamp without time zone,
  qrShape USER-DEFINED NOT NULL DEFAULT 'ROUNDED'::"QRShapeType",
  designId text,
  themeOverride jsonb,
  showProfile boolean NOT NULL DEFAULT true,
  showHeading boolean NOT NULL DEFAULT true,
  showContact boolean NOT NULL DEFAULT true,
  showSocial boolean NOT NULL DEFAULT true,
  showLinks boolean NOT NULL DEFAULT true,
  showAppointment boolean NOT NULL DEFAULT true,
  showBusinessDetails boolean NOT NULL DEFAULT true,
  showExtraSections boolean NOT NULL DEFAULT true,
  backgroundColor text NOT NULL DEFAULT '#000000'::text,
  accentColor text NOT NULL DEFAULT '#008001'::text,
  accentLight text NOT NULL DEFAULT '#49B618'::text,
  textColor text NOT NULL DEFAULT '#FFFFFF'::text,
  cardColor text NOT NULL DEFAULT '#0a0a0a'::text,
  cardRadius integer NOT NULL DEFAULT 16,
  fontFamily USER-DEFINED NOT NULL DEFAULT 'INTER'::"FontFamily",
  nameFontSize integer NOT NULL DEFAULT 24,
  bodyFontSize integer NOT NULL DEFAULT 14,
  boldHeadings boolean NOT NULL DEFAULT false,
  phoneBgType USER-DEFINED NOT NULL DEFAULT 'SOLID'::"WallpaperType",
  phoneBgPreset text,
  phoneBgColor1 text NOT NULL DEFAULT '#000000'::text,
  phoneBgColor2 text NOT NULL DEFAULT '#0a0a0a'::text,
  phoneBgAngle integer NOT NULL DEFAULT 180,
  shadowIntensity USER-DEFINED NOT NULL DEFAULT 'MEDIUM'::"ShadowIntensity",
  glowEffect boolean NOT NULL DEFAULT false,
  thumbnailUrl text,
  metaTitle text,
  metaDescription text,
  ogImage text,
  totalViews integer NOT NULL DEFAULT 0,
  totalTaps integer NOT NULL DEFAULT 0,
  totalScans integer NOT NULL DEFAULT 0,
  totalSaves integer NOT NULL DEFAULT 0,
  totalShares integer NOT NULL DEFAULT 0,
  uniqueVisitors integer NOT NULL DEFAULT 0,
  totalLinkClicks integer NOT NULL DEFAULT 0,
  thisWeekViews integer NOT NULL DEFAULT 0,
  thisWeekTaps integer NOT NULL DEFAULT 0,
  monthlyTapGoal integer,
  monthlyViewGoal integer,
  completionScore integer NOT NULL DEFAULT 0,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt timestamp without time zone NOT NULL,
  publishedAt timestamp without time zone,
  lastSharedAt timestamp without time zone,
  deletedAt timestamp without time zone,
  CONSTRAINT Card_pkey PRIMARY KEY (id),
  CONSTRAINT Card_userId_fkey FOREIGN KEY (userId) REFERENCES public.User(id),
  CONSTRAINT Card_businessProfileId_fkey FOREIGN KEY (businessProfileId) REFERENCES public.BusinessProfile(id),
  CONSTRAINT Card_designId_fkey FOREIGN KEY (designId) REFERENCES public.CardDesign(id)
);
CREATE TABLE public.CardAnalytics (
  id text NOT NULL,
  cardId text NOT NULL,
  date date NOT NULL,
  hour integer,
  views integer NOT NULL DEFAULT 0,
  uniqueViews integer NOT NULL DEFAULT 0,
  taps integer NOT NULL DEFAULT 0,
  uniqueTaps integer NOT NULL DEFAULT 0,
  scans integer NOT NULL DEFAULT 0,
  uniqueScans integer NOT NULL DEFAULT 0,
  saves integer NOT NULL DEFAULT 0,
  shares integer NOT NULL DEFAULT 0,
  linkClicks integer NOT NULL DEFAULT 0,
  nfcTraffic integer NOT NULL DEFAULT 0,
  qrTraffic integer NOT NULL DEFAULT 0,
  linkTraffic integer NOT NULL DEFAULT 0,
  directTraffic integer NOT NULL DEFAULT 0,
  searchTraffic integer NOT NULL DEFAULT 0,
  socialTraffic integer NOT NULL DEFAULT 0,
  referralTraffic integer NOT NULL DEFAULT 0,
  deviceBreakdown jsonb,
  browserBreakdown jsonb,
  osBreakdown jsonb,
  countryBreakdown jsonb,
  cityBreakdown jsonb,
  avgDurationSeconds double precision,
  maxDurationSeconds integer,
  avgScrollDepth double precision,
  totalSessions integer NOT NULL DEFAULT 0,
  leadsGenerated integer NOT NULL DEFAULT 0,
  conversionRate double precision,
  linkClickBreakdown jsonb,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt timestamp without time zone NOT NULL,
  CONSTRAINT CardAnalytics_pkey PRIMARY KEY (id),
  CONSTRAINT CardAnalytics_cardId_fkey FOREIGN KEY (cardId) REFERENCES public.Card(id)
);
CREATE TABLE public.CardDesign (
  id text NOT NULL,
  userId text,
  name text NOT NULL,
  description text,
  isPreset boolean NOT NULL DEFAULT false,
  isPublic boolean NOT NULL DEFAULT false,
  accentColor text NOT NULL DEFAULT '#008001'::text,
  accentLight text NOT NULL DEFAULT '#49B618'::text,
  backgroundColor text NOT NULL DEFAULT '#000000'::text,
  cardColor text NOT NULL DEFAULT '#0a0a0a'::text,
  textPrimary text NOT NULL DEFAULT '#FFFFFF'::text,
  textMuted text NOT NULL DEFAULT '#A0A0A0'::text,
  fontFamily USER-DEFINED NOT NULL DEFAULT 'INTER'::"FontFamily",
  nameFontSize integer NOT NULL DEFAULT 24,
  bodyFontSize integer NOT NULL DEFAULT 14,
  boldHeadings boolean NOT NULL DEFAULT false,
  cardRadius integer NOT NULL DEFAULT 16,
  shadowIntensity USER-DEFINED NOT NULL DEFAULT 'MEDIUM'::"ShadowIntensity",
  glowEffect boolean NOT NULL DEFAULT false,
  phoneBgType USER-DEFINED NOT NULL DEFAULT 'SOLID'::"WallpaperType",
  phoneBgPreset text,
  phoneBgColor1 text NOT NULL DEFAULT '#000000'::text,
  phoneBgColor2 text NOT NULL DEFAULT '#0a0a0a'::text,
  phoneBgAngle integer NOT NULL DEFAULT 180,
  thumbnailUrl text,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt timestamp without time zone NOT NULL,
  CONSTRAINT CardDesign_pkey PRIMARY KEY (id),
  CONSTRAINT CardDesign_userId_fkey FOREIGN KEY (userId) REFERENCES public.User(id)
);
CREATE TABLE public.CardInteraction (
  id text NOT NULL,
  cardId text NOT NULL,
  type text NOT NULL,
  visitorId text,
  fingerprint text,
  ipAddress text,
  userAgent text,
  deviceType USER-DEFINED NOT NULL DEFAULT 'UNKNOWN'::"DeviceType",
  browser text,
  os text,
  city text,
  country text,
  countryCode text,
  region text,
  latitude double precision,
  longitude double precision,
  referrer text,
  utmSource text,
  utmMedium text,
  utmCampaign text,
  utmContent text,
  linkId text,
  linkLabel text,
  durationSeconds integer,
  scrollDepth integer,
  actionsPerformed jsonb,
  screenWidth integer,
  screenHeight integer,
  isMobile boolean,
  isTablet boolean,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT CardInteraction_pkey PRIMARY KEY (id),
  CONSTRAINT CardInteraction_cardId_fkey FOREIGN KEY (cardId) REFERENCES public.Card(id)
);
CREATE TABLE public.CardShare (
  id text NOT NULL,
  cardId text NOT NULL,
  method text NOT NULL,
  recipientEmail text,
  recipientPhone text,
  recipientName text,
  sharedUrl text NOT NULL,
  sharedByIp text,
  sharedByVisitorId text,
  wasOpened boolean NOT NULL DEFAULT false,
  openedAt timestamp without time zone,
  wasEngaged boolean NOT NULL DEFAULT false,
  engagedAt timestamp without time zone,
  wasConverted boolean NOT NULL DEFAULT false,
  convertedAt timestamp without time zone,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT CardShare_pkey PRIMARY KEY (id),
  CONSTRAINT CardShare_cardId_fkey FOREIGN KEY (cardId) REFERENCES public.Card(id)
);
CREATE TABLE public.ColorPalette (
  id text NOT NULL,
  name text NOT NULL,
  emoji text,
  accent text NOT NULL,
  accentLight text NOT NULL,
  bg text NOT NULL,
  card text NOT NULL,
  textPrimary text NOT NULL,
  textMuted text NOT NULL,
  wallpaper text,
  isPreset boolean NOT NULL DEFAULT false,
  displayOrder integer NOT NULL DEFAULT 0,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ColorPalette_pkey PRIMARY KEY (id)
);
CREATE TABLE public.CustomLink (
  id text NOT NULL,
  businessProfileId text NOT NULL,
  label text NOT NULL,
  url text NOT NULL,
  icon text,
  color text,
  displayOrder integer NOT NULL DEFAULT 0,
  enabled boolean NOT NULL DEFAULT true,
  clickTracking boolean NOT NULL DEFAULT true,
  totalClicks integer NOT NULL DEFAULT 0,
  uniqueClicks integer NOT NULL DEFAULT 0,
  lastClickedAt timestamp without time zone,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt timestamp without time zone NOT NULL,
  CONSTRAINT CustomLink_pkey PRIMARY KEY (id),
  CONSTRAINT CustomLink_businessProfileId_fkey FOREIGN KEY (businessProfileId) REFERENCES public.BusinessProfile(id)
);
CREATE TABLE public.DashboardStats (
  id text NOT NULL,
  userId text NOT NULL,
  todayTaps integer NOT NULL DEFAULT 0,
  todayViews integer NOT NULL DEFAULT 0,
  todayLeads integer NOT NULL DEFAULT 0,
  weekTaps integer NOT NULL DEFAULT 0,
  weekViews integer NOT NULL DEFAULT 0,
  weekLeads integer NOT NULL DEFAULT 0,
  monthTaps integer NOT NULL DEFAULT 0,
  monthViews integer NOT NULL DEFAULT 0,
  monthLeads integer NOT NULL DEFAULT 0,
  tapsTrend double precision NOT NULL DEFAULT 0,
  viewsTrend double precision NOT NULL DEFAULT 0,
  leadsTrend double precision NOT NULL DEFAULT 0,
  conversionRate double precision NOT NULL DEFAULT 0,
  topCardId text,
  topCardName text,
  topCardTaps integer NOT NULL DEFAULT 0,
  updatedAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT DashboardStats_pkey PRIMARY KEY (id),
  CONSTRAINT DashboardStats_userId_fkey FOREIGN KEY (userId) REFERENCES public.User(id)
);
CREATE TABLE public.EmailTemplate (
  id text NOT NULL,
  name text NOT NULL,
  slug text NOT NULL,
  subject text NOT NULL,
  body text NOT NULL,
  preheader text,
  type text NOT NULL,
  trigger text,
  variables ARRAY,
  isActive boolean NOT NULL DEFAULT true,
  isSystem boolean NOT NULL DEFAULT false,
  version integer NOT NULL DEFAULT 1,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt timestamp without time zone NOT NULL,
  CONSTRAINT EmailTemplate_pkey PRIMARY KEY (id)
);
CREATE TABLE public.ExtraSection (
  id text NOT NULL,
  businessProfileId text NOT NULL,
  type USER-DEFINED NOT NULL,
  label text NOT NULL,
  displayOrder integer NOT NULL DEFAULT 0,
  enabled boolean NOT NULL DEFAULT true,
  expanded boolean NOT NULL DEFAULT true,
  data jsonb NOT NULL DEFAULT '{}'::jsonb,
  showOnCard boolean NOT NULL DEFAULT true,
  showOnPreview boolean NOT NULL DEFAULT true,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt timestamp without time zone NOT NULL,
  CONSTRAINT ExtraSection_pkey PRIMARY KEY (id),
  CONSTRAINT ExtraSection_businessProfileId_fkey FOREIGN KEY (businessProfileId) REFERENCES public.BusinessProfile(id)
);
CREATE TABLE public.Goal (
  id text NOT NULL,
  userId text NOT NULL,
  name text NOT NULL,
  type USER-DEFINED NOT NULL,
  targetValue integer NOT NULL,
  currentValue integer NOT NULL DEFAULT 0,
  period text NOT NULL,
  startDate timestamp without time zone NOT NULL,
  endDate timestamp without time zone NOT NULL,
  status text NOT NULL DEFAULT 'active'::text,
  progress double precision NOT NULL DEFAULT 0,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt timestamp without time zone NOT NULL,
  CONSTRAINT Goal_pkey PRIMARY KEY (id),
  CONSTRAINT Goal_userId_fkey FOREIGN KEY (userId) REFERENCES public.User(id)
);
CREATE TABLE public.Invoice (
  id text NOT NULL,
  userId text NOT NULL,
  invoiceNumber text NOT NULL,
  subscriptionId text,
  periodStart timestamp without time zone NOT NULL,
  periodEnd timestamp without time zone NOT NULL,
  items jsonb NOT NULL,
  subtotal double precision NOT NULL,
  tax double precision NOT NULL DEFAULT 0,
  taxRate double precision NOT NULL DEFAULT 0,
  discount double precision NOT NULL DEFAULT 0,
  total double precision NOT NULL,
  currency text NOT NULL DEFAULT 'USD'::text,
  status USER-DEFINED NOT NULL DEFAULT 'PENDING'::"PaymentStatus",
  paidAt timestamp without time zone,
  dueDate timestamp without time zone,
  stripeInvoiceId text,
  stripePaymentIntent text,
  stripeSubscriptionId text,
  stripeChargeId text,
  pdfUrl text,
  notes text,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt timestamp without time zone NOT NULL,
  CONSTRAINT Invoice_pkey PRIMARY KEY (id),
  CONSTRAINT Invoice_userId_fkey FOREIGN KEY (userId) REFERENCES public.User(id)
);
CREATE TABLE public.Lead (
  id text NOT NULL,
  userId text NOT NULL,
  businessProfileId text NOT NULL,
  cardId text,
  name text NOT NULL,
  firstName text,
  lastName text,
  email text,
  phone text,
  company text,
  jobTitle text,
  avatar text,
  notes text,
  tags ARRAY,
  source USER-DEFINED NOT NULL,
  sourceDetail text,
  utmSource text,
  utmCampaign text,
  engagementScore integer NOT NULL DEFAULT 0,
  interestLevel integer NOT NULL DEFAULT 0,
  status USER-DEFINED NOT NULL DEFAULT 'NEW'::"LeadStatus",
  isFavorite boolean NOT NULL DEFAULT false,
  isArchived boolean NOT NULL DEFAULT false,
  leadScore integer NOT NULL DEFAULT 0,
  marketingConsent boolean NOT NULL DEFAULT false,
  consentGivenAt timestamp without time zone,
  gdprConsent boolean NOT NULL DEFAULT false,
  estimatedValue double precision,
  lastContactedAt timestamp without time zone,
  lastEngagedAt timestamp without time zone,
  interactionCount integer NOT NULL DEFAULT 0,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt timestamp without time zone NOT NULL,
  CONSTRAINT Lead_pkey PRIMARY KEY (id),
  CONSTRAINT Lead_userId_fkey FOREIGN KEY (userId) REFERENCES public.User(id),
  CONSTRAINT Lead_businessProfileId_fkey FOREIGN KEY (businessProfileId) REFERENCES public.BusinessProfile(id),
  CONSTRAINT Lead_cardId_fkey FOREIGN KEY (cardId) REFERENCES public.Card(id)
);
CREATE TABLE public.LeadActivity (
  id text NOT NULL,
  leadId text NOT NULL,
  type text NOT NULL,
  title text NOT NULL,
  description text,
  metadata jsonb,
  city text,
  country text,
  deviceType USER-DEFINED,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT LeadActivity_pkey PRIMARY KEY (id),
  CONSTRAINT LeadActivity_leadId_fkey FOREIGN KEY (leadId) REFERENCES public.Lead(id)
);
CREATE TABLE public.LeadInteraction (
  id text NOT NULL,
  leadId text NOT NULL,
  type text NOT NULL,
  subject text,
  body text,
  direction text,
  outcome text,
  scheduledAt timestamp without time zone,
  startedAt timestamp without time zone,
  completedAt timestamp without time zone,
  durationSeconds integer,
  metadata jsonb,
  attachments jsonb,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT LeadInteraction_pkey PRIMARY KEY (id),
  CONSTRAINT LeadInteraction_leadId_fkey FOREIGN KEY (leadId) REFERENCES public.Lead(id)
);
CREATE TABLE public.LeadTask (
  id text NOT NULL,
  leadId text NOT NULL,
  title text NOT NULL,
  description text,
  status text NOT NULL DEFAULT 'pending'::text,
  priority USER-DEFINED NOT NULL DEFAULT 'MEDIUM'::"TaskPriority",
  dueDate timestamp without time zone,
  startedAt timestamp without time zone,
  completedAt timestamp without time zone,
  reminderAt timestamp without time zone,
  reminderSent boolean NOT NULL DEFAULT false,
  assignedTo text,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt timestamp without time zone NOT NULL,
  CONSTRAINT LeadTask_pkey PRIMARY KEY (id),
  CONSTRAINT LeadTask_leadId_fkey FOREIGN KEY (leadId) REFERENCES public.Lead(id)
);
CREATE TABLE public.LinkClick (
  id text NOT NULL,
  cardId text NOT NULL,
  socialLinkId text,
  customLinkId text,
  visitorId text,
  ipAddress text,
  userAgent text,
  deviceType USER-DEFINED NOT NULL DEFAULT 'UNKNOWN'::"DeviceType",
  city text,
  country text,
  countryCode text,
  referrer text,
  utmSource text,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT LinkClick_pkey PRIMARY KEY (id),
  CONSTRAINT LinkClick_cardId_fkey FOREIGN KEY (cardId) REFERENCES public.Card(id),
  CONSTRAINT LinkClick_socialLinkId_fkey FOREIGN KEY (socialLinkId) REFERENCES public.SocialLink(id),
  CONSTRAINT LinkClick_customLinkId_fkey FOREIGN KEY (customLinkId) REFERENCES public.CustomLink(id)
);
CREATE TABLE public.NfcCard (
  id text NOT NULL,
  cardId text,
  userId text,
  uid text NOT NULL,
  chipType text,
  ndefCapacity integer,
  physicalCardId text,
  cardMaterial text,
  cardColors jsonb,
  cardWeight double precision,
  assignedAt timestamp without time zone,
  isActivated boolean NOT NULL DEFAULT false,
  isLinked boolean NOT NULL DEFAULT false,
  isAssigned boolean NOT NULL DEFAULT false,
  activationCode text,
  writeCount integer NOT NULL DEFAULT 0,
  lastWrittenAt timestamp without time zone,
  lastTapAt timestamp without time zone,
  totalTaps integer NOT NULL DEFAULT 0,
  productId text,
  sku text,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt timestamp without time zone NOT NULL,
  CONSTRAINT NfcCard_pkey PRIMARY KEY (id),
  CONSTRAINT NfcCard_userId_fkey FOREIGN KEY (userId) REFERENCES public.User(id),
  CONSTRAINT NfcCard_cardId_fkey FOREIGN KEY (cardId) REFERENCES public.Card(id)
);
CREATE TABLE public.Notification (
  id text NOT NULL,
  userId text NOT NULL,
  type USER-DEFINED NOT NULL,
  title text NOT NULL,
  message text NOT NULL,
  data jsonb,
  read boolean NOT NULL DEFAULT false,
  readAt timestamp without time zone,
  actionUrl text,
  actionLabel text,
  emailSent boolean NOT NULL DEFAULT false,
  emailSentAt timestamp without time zone,
  pushSent boolean NOT NULL DEFAULT false,
  pushSentAt timestamp without time zone,
  priority text NOT NULL DEFAULT 'normal'::text,
  sourceId text,
  sourceType text,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT Notification_pkey PRIMARY KEY (id),
  CONSTRAINT Notification_userId_fkey FOREIGN KEY (userId) REFERENCES public.User(id)
);
CREATE TABLE public.Order (
  id text NOT NULL,
  userId text NOT NULL,
  orderNumber text NOT NULL,
  items jsonb NOT NULL,
  subtotal double precision NOT NULL,
  tax double precision NOT NULL DEFAULT 0,
  taxRate double precision NOT NULL DEFAULT 0,
  discount double precision NOT NULL DEFAULT 0,
  discountCode text,
  shipping double precision NOT NULL DEFAULT 0,
  total double precision NOT NULL,
  currency text NOT NULL DEFAULT 'USD'::text,
  status USER-DEFINED NOT NULL DEFAULT 'PENDING'::"OrderStatus",
  shippingName text,
  shippingPhone text,
  shippingAddress jsonb,
  shippingMethod text,
  shippingCost double precision,
  trackingNumber text,
  trackingUrl text,
  carrier text,
  paymentMethodId text,
  paymentIntentId text,
  paidAt timestamp without time zone,
  fulfilledAt timestamp without time zone,
  shippedAt timestamp without time zone,
  deliveredAt timestamp without time zone,
  customerNotes text,
  internalNotes text,
  refundAmount double precision NOT NULL DEFAULT 0,
  refundReason text,
  refundedAt timestamp without time zone,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt timestamp without time zone NOT NULL,
  CONSTRAINT Order_pkey PRIMARY KEY (id),
  CONSTRAINT Order_userId_fkey FOREIGN KEY (userId) REFERENCES public.User(id)
);
CREATE TABLE public.OrderItem (
  id text NOT NULL,
  orderId text NOT NULL,
  productId text NOT NULL,
  sku text,
  name text NOT NULL,
  description text,
  quantity integer NOT NULL,
  unitPrice double precision NOT NULL,
  total double precision NOT NULL,
  options jsonb,
  weight double precision,
  dimensions jsonb,
  CONSTRAINT OrderItem_pkey PRIMARY KEY (id),
  CONSTRAINT OrderItem_orderId_fkey FOREIGN KEY (orderId) REFERENCES public.Order(id),
  CONSTRAINT OrderItem_productId_fkey FOREIGN KEY (productId) REFERENCES public.Product(id)
);
CREATE TABLE public.PaymentMethod (
  id text NOT NULL,
  userId text NOT NULL,
  stripePaymentMethodId text NOT NULL,
  brand USER-DEFINED NOT NULL,
  last4 text NOT NULL,
  expMonth integer NOT NULL,
  expYear integer NOT NULL,
  funding text,
  displayName text,
  isDefault boolean NOT NULL DEFAULT false,
  billingName text,
  billingAddress jsonb,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt timestamp without time zone NOT NULL,
  CONSTRAINT PaymentMethod_pkey PRIMARY KEY (id),
  CONSTRAINT PaymentMethod_userId_fkey FOREIGN KEY (userId) REFERENCES public.User(id)
);
CREATE TABLE public.Plan (
  id text NOT NULL,
  name text NOT NULL,
  tier USER-DEFINED NOT NULL,
  priceMonthly double precision NOT NULL,
  priceYearly double precision NOT NULL,
  currency text NOT NULL DEFAULT 'USD'::text,
  maxCards integer NOT NULL,
  maxTaps integer NOT NULL,
  maxStorageMb integer NOT NULL,
  maxLeads integer NOT NULL,
  maxTeamMembers integer NOT NULL DEFAULT 1,
  features ARRAY,
  description text,
  popular boolean NOT NULL DEFAULT false,
  trialDays integer NOT NULL DEFAULT 0,
  isActive boolean NOT NULL DEFAULT true,
  displayOrder integer NOT NULL DEFAULT 0,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt timestamp without time zone NOT NULL,
  CONSTRAINT Plan_pkey PRIMARY KEY (id)
);
CREATE TABLE public.Product (
  id text NOT NULL,
  name text NOT NULL,
  slug text NOT NULL,
  description text,
  shortDescription text,
  price double precision NOT NULL,
  compareAtPrice double precision,
  costPrice double precision,
  sku text,
  barcode text,
  inventory integer NOT NULL DEFAULT 0,
  trackInventory boolean NOT NULL DEFAULT true,
  lowStockThreshold integer NOT NULL DEFAULT 10,
  weight double precision,
  dimensions jsonb,
  images jsonb,
  thumbnailUrl text,
  category text,
  tags ARRAY,
  status text NOT NULL DEFAULT 'active'::text,
  isDigital boolean NOT NULL DEFAULT false,
  nfcChipType text,
  cardMaterial text,
  cardColors jsonb,
  requiresShipping boolean NOT NULL DEFAULT true,
  freeShipping boolean NOT NULL DEFAULT false,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt timestamp without time zone NOT NULL,
  CONSTRAINT Product_pkey PRIMARY KEY (id)
);
CREATE TABLE public.QRPresetLogo (
  id text NOT NULL,
  name text NOT NULL,
  category text NOT NULL,
  icon text NOT NULL,
  isPreset boolean NOT NULL DEFAULT true,
  displayOrder integer NOT NULL DEFAULT 0,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT QRPresetLogo_pkey PRIMARY KEY (id)
);
CREATE TABLE public.QRSticker (
  id text NOT NULL,
  name text NOT NULL,
  category text NOT NULL,
  style text NOT NULL,
  defaultWidth integer NOT NULL DEFAULT 60,
  defaultPosition text NOT NULL DEFAULT 'bottom-right'::text,
  defaultColor text,
  defaultOutline text,
  isPreset boolean NOT NULL DEFAULT true,
  displayOrder integer NOT NULL DEFAULT 0,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT QRSticker_pkey PRIMARY KEY (id)
);
CREATE TABLE public.QRTemplate (
  id text NOT NULL,
  userId text,
  name text NOT NULL,
  description text,
  isPreset boolean NOT NULL DEFAULT false,
  isPublic boolean NOT NULL DEFAULT false,
  shapeId USER-DEFINED NOT NULL DEFAULT 'ROUNDED'::"QRShapeType",
  dotShape USER-DEFINED NOT NULL DEFAULT 'ROUNDED'::"QRDotShape",
  bodyScale double precision NOT NULL DEFAULT 0.8,
  eyeFrameStyle USER-DEFINED NOT NULL DEFAULT 'ROUNDED'::"QREyeFrameStyle",
  eyeBallStyle USER-DEFINED NOT NULL DEFAULT 'CIRCLE'::"QREyeBallStyle",
  fgColor text NOT NULL DEFAULT '#FFFFFF'::text,
  bgColor text NOT NULL DEFAULT '#000000'::text,
  accentFgEnabled boolean NOT NULL DEFAULT false,
  accentFg text,
  accentBgEnabled boolean NOT NULL DEFAULT false,
  accentBg text,
  strokeEnabled boolean NOT NULL DEFAULT false,
  strokeColor text NOT NULL DEFAULT '#FFFFFF'::text,
  gradEnabled boolean NOT NULL DEFAULT false,
  gradStops jsonb,
  gradAngle integer NOT NULL DEFAULT 180,
  logoId text,
  customLogoUrl text,
  stickerId text,
  stickerData jsonb,
  decorateImageUrl text,
  decoratePosition text,
  decorateComposite bytea,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt timestamp without time zone NOT NULL,
  CONSTRAINT QRTemplate_pkey PRIMARY KEY (id),
  CONSTRAINT QRTemplate_userId_fkey FOREIGN KEY (userId) REFERENCES public.User(id)
);
CREATE TABLE public.Session (
  id text NOT NULL,
  userId text NOT NULL,
  token text NOT NULL,
  device text,
  deviceType USER-DEFINED NOT NULL DEFAULT 'WEB'::"DeviceType",
  browser text,
  os text,
  ipAddress text,
  location text,
  isCurrent boolean NOT NULL DEFAULT false,
  userAgent text,
  expiresAt timestamp without time zone NOT NULL,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  lastActiveAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT Session_pkey PRIMARY KEY (id),
  CONSTRAINT Session_userId_fkey FOREIGN KEY (userId) REFERENCES public.User(id)
);
CREATE TABLE public.SocialLink (
  id text NOT NULL,
  businessProfileId text NOT NULL,
  platform USER-DEFINED NOT NULL,
  handle text NOT NULL,
  url text,
  label text,
  icon text,
  displayOrder integer NOT NULL DEFAULT 0,
  enabled boolean NOT NULL DEFAULT true,
  totalClicks integer NOT NULL DEFAULT 0,
  uniqueClicks integer NOT NULL DEFAULT 0,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt timestamp without time zone NOT NULL,
  CONSTRAINT SocialLink_pkey PRIMARY KEY (id),
  CONSTRAINT SocialLink_businessProfileId_fkey FOREIGN KEY (businessProfileId) REFERENCES public.BusinessProfile(id)
);
CREATE TABLE public.User (
  id text NOT NULL,
  email text NOT NULL,
  emailVerified boolean NOT NULL DEFAULT false,
  passwordHash text,
  name text,
  phone text,
  avatar text,
  role USER-DEFINED NOT NULL DEFAULT 'USER'::"UserRole",
  timezone text NOT NULL DEFAULT 'UTC'::text,
  language text NOT NULL DEFAULT 'en'::text,
  theme USER-DEFINED NOT NULL DEFAULT 'DARK'::"Theme",
  compactMode boolean NOT NULL DEFAULT false,
  subscriptionId text,
  planTier USER-DEFINED NOT NULL DEFAULT 'FREE'::"PlanTier",
  subscriptionStatus USER-DEFINED NOT NULL DEFAULT 'ACTIVE'::"SubscriptionStatus",
  subscriptionEndsAt timestamp without time zone,
  maxCards integer NOT NULL DEFAULT 1,
  maxTaps integer NOT NULL DEFAULT 500,
  maxStorageMb integer NOT NULL DEFAULT 256,
  maxLeads integer NOT NULL DEFAULT 100,
  totalCards integer NOT NULL DEFAULT 0,
  totalTaps integer NOT NULL DEFAULT 0,
  totalViews integer NOT NULL DEFAULT 0,
  totalLeads integer NOT NULL DEFAULT 0,
  totalOrders integer NOT NULL DEFAULT 0,
  totalSpent double precision NOT NULL DEFAULT 0,
  profilePublic boolean NOT NULL DEFAULT true,
  showEmail boolean NOT NULL DEFAULT true,
  showPhone boolean NOT NULL DEFAULT true,
  analyticsOptIn boolean NOT NULL DEFAULT true,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt timestamp without time zone NOT NULL,
  lastLoginAt timestamp without time zone,
  emailVerifiedAt timestamp without time zone,
  deletedAt timestamp without time zone,
  CONSTRAINT User_pkey PRIMARY KEY (id)
);
CREATE TABLE public.UserConnectedAccount (
  id text NOT NULL,
  userId text NOT NULL,
  platform text NOT NULL,
  connected boolean NOT NULL DEFAULT false,
  connectedAt timestamp without time zone,
  accountId text,
  accountName text,
  accountUrl text,
  accountAvatar text,
  accessToken text,
  refreshToken text,
  expiresAt timestamp without time zone,
  scopes ARRAY,
  lastSyncedAt timestamp without time zone,
  syncStatus text,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt timestamp without time zone NOT NULL,
  CONSTRAINT UserConnectedAccount_pkey PRIMARY KEY (id),
  CONSTRAINT UserConnectedAccount_userId_fkey FOREIGN KEY (userId) REFERENCES public.User(id)
);
CREATE TABLE public.WallpaperPreset (
  id text NOT NULL,
  name text NOT NULL,
  style text NOT NULL,
  color1 text NOT NULL,
  color2 text,
  angle integer,
  thumb text,
  isPreset boolean NOT NULL DEFAULT false,
  displayOrder integer NOT NULL DEFAULT 0,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT WallpaperPreset_pkey PRIMARY KEY (id)
);
CREATE TABLE public.Webhook (
  id text NOT NULL,
  userId text,
  name text NOT NULL,
  url text NOT NULL,
  secret text,
  events ARRAY,
  headers jsonb,
  isActive boolean NOT NULL DEFAULT true,
  maxRetries integer NOT NULL DEFAULT 3,
  retryCount integer NOT NULL DEFAULT 0,
  lastTriggeredAt timestamp without time zone,
  lastSuccessAt timestamp without time zone,
  lastError text,
  lastResponseCode integer,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt timestamp without time zone NOT NULL,
  CONSTRAINT Webhook_pkey PRIMARY KEY (id),
  CONSTRAINT Webhook_userId_fkey FOREIGN KEY (userId) REFERENCES public.User(id)
);
CREATE TABLE public.WebhookDelivery (
  id text NOT NULL,
  webhookId text NOT NULL,
  event text NOT NULL,
  payload jsonb NOT NULL,
  responseCode integer,
  responseBody text,
  error text,
  attempts integer NOT NULL DEFAULT 1,
  delivered boolean NOT NULL DEFAULT false,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT WebhookDelivery_pkey PRIMARY KEY (id),
  CONSTRAINT WebhookDelivery_webhookId_fkey FOREIGN KEY (webhookId) REFERENCES public.Webhook(id)
);